/**
 * SBURB – Game Configuration
 * All static data from Homestuck (Andrew Hussie) canon.
 */

const CONFIG = {

  // ─── BETA KIDS ─────────────────────────────────────────────────────────────
  BETA_KIDS: [
    {
      id: 'john',
      name: 'John Egbert',
      handle: 'ectoBiologist',
      initials: 'EB',
      color: '#0715cd',
      aspect: 'Breath',
      playerClass: 'Heir',
      title: 'Heir of Breath',
      planet: 'LOWAS',
      planetFull: 'Land of Wind and Shade',
      dreamMoon: 'Prospit',
      strife: 'Hammerkind',
      startWeapon: { id: 'crappy_sledgehammer', name: 'Crappy Sledgehammer', atk: 4, icon: '🔨' },
      sylladexModus: 'Stack',
      consorts: 'Salamanders',
      consortIcon: '🦎',
      server: 'rose',
      client: 'dave',
      denizen: 'Typheus',
      sprite: {
        name: 'Nannasprite',
        protoObject: "Nanna's Ashes",
        icon: '👵',
        power: 'Gives cooking advice and crucial exposition. HP +15.',
        hpBonus: 15, atkBonus: 0,
      },
      questSummary: 'Free the wind. The salamanders of LOWAS have been waiting centuries for the Heir of Breath to unlock the imprisoned wind currents from the underground pipelines. Clear the smoke from the smokestacks and let the wind breathe again.',
      introMessages: [
        { handle: 'EB', text: 'oh man oh man oh man!' },
        { handle: 'EB', text: "i just got the beta for sburb in the mail!" },
        { handle: 'EB', text: "dad got it for me as a birthday present!!" },
        { handle: 'EB', text: "have you heard about this game? it apparently does stuff to your actual house!" },
        { handle: 'EB', text: "rose will you be my server player?? i'm installing it right now." },
      ],
      roomDesc: "Your name is JOHN EGBERT. You are a young man standing in your bedroom. It just so happens that today, the 13th of April, 2009, is the day you receive a very special gift. You have a passion for GHOSTBUSTERS and MAGIC TRICKS and an appreciation for your late grandmother NANNA's COOKING. Your DAD means well.",
      icon: '🧑',
      baseHp: 100, baseAtk: 5,
    },
    {
      id: 'rose',
      name: 'Rose Lalonde',
      handle: 'tentacleTherapist',
      initials: 'TT',
      color: '#b536da',
      aspect: 'Light',
      playerClass: 'Seer',
      title: 'Seer of Light',
      planet: 'LOLAR',
      planetFull: 'Land of Light and Rain',
      dreamMoon: 'Derse',
      strife: 'Needlekind',
      startWeapon: { id: 'knitting_needles', name: 'Knitting Needles', atk: 5, icon: '🪡' },
      sylladexModus: 'Tree',
      consorts: 'Iguanas',
      consortIcon: '🦎',
      server: 'dave',
      client: 'john',
      denizen: 'Nix',
      sprite: {
        name: 'Jaspersprite',
        protoObject: 'Jaspers the Cat',
        icon: '🐈',
        power: 'Speaks in broken cat-speech. Cryptic guidance. ATK +10.',
        hpBonus: 0, atkBonus: 10,
      },
      questSummary: "Navigate the paradox of light and darkness on LOLAR. The iguanas need you. Something corrupts Skaia's light as it refracts through the smoke-clouds, turning the rain toxic. As Seer of Light, find the truth and clear the path.",
      introMessages: [
        { handle: 'TT', text: "Good morning. Or rather, good afternoon, if my clock is to be believed." },
        { handle: 'TT', text: "I understand we've both received the SBURB beta today." },
        { handle: 'TT', text: "How curious that the delivery date coincides with your birthday, John." },
        { handle: 'TT', text: "I've been studying the game's documentation. The server-client dynamic is fascinating — one player literally controls the other's environment." },
        { handle: 'TT', text: "I'll be your server player, if you'll have me. Do try not to let me accidentally drop a piano on you." },
      ],
      roomDesc: "Your name is ROSE LALONDE. You live with your ECTOMOM in a house adorned with WIZARD STATUES and proliferations of YARN. Your cat JASPERS has recently passed. You study TOMES OF ELDRITCH LORE and are an avid KNITTER with an interest in ADVANCED MYTHOLOGICAL STUDIES and AMATEUR PSYCHOLOGY.",
      icon: '🧑‍🎤',
      baseHp: 90, baseAtk: 6,
    },
    {
      id: 'dave',
      name: 'Dave Strider',
      handle: 'turntechGodhead',
      initials: 'TG',
      color: '#e00707',
      aspect: 'Time',
      playerClass: 'Knight',
      title: 'Knight of Time',
      planet: 'LOHAC',
      planetFull: 'Land of Heat and Clockwork',
      dreamMoon: 'Derse',
      strife: 'Bladekind',
      startWeapon: { id: 'broken_sword', name: 'Broken Sword of the 21st Century', atk: 3, icon: '⚔️' },
      sylladexModus: 'Queue',
      consorts: 'Crocodiles',
      consortIcon: '🐊',
      server: 'john',
      client: 'rose',
      denizen: 'Hephaestus',
      sprite: {
        name: 'Calsprite',
        protoObject: 'Lil Cal (puppet)',
        icon: '🤡',
        power: "Eldritch laughter. Enemies sometimes flee in terror. ATK +5. HP +5.",
        hpBonus: 5, atkBonus: 5,
      },
      questSummary: "Fix the broken clockwork of LOHAC. The entire planet is a massive gear mechanism — a clock the size of a world — and it has ground to a halt. The crocodiles have lost all sense of time. As Knight of Time, repair the gears and oil the mechanism.",
      introMessages: [
        { handle: 'TG', text: "yo" },
        { handle: 'TG', text: "i heard you got the sburb beta" },
        { handle: 'TG', text: "yeah i got it too bro has like a hundred copies of the server disc dont ask me why" },
        { handle: 'TG', text: "this game is apparently kind of a big deal like literally rearranges reality or whatever" },
        { handle: 'TG', text: "pretty cool i guess not that i care" },
        { handle: 'TG', text: "ok i care a little" },
      ],
      roomDesc: "Your name is DAVE STRIDER. You live with your BRO in a sick Houston apartment covered wall-to-wall in IRONIC ART and PUPPET PARAPHERNALIA. You are an AMATEUR DJ and AMATEUR PHOTOGRAPHER. You run a WEBCOMIC called SWEET BRO AND HELLA JEFF. Your BRO is incredibly hard to impress.",
      icon: '😎',
      baseHp: 95, baseAtk: 7,
    },
    {
      id: 'jade',
      name: 'Jade Harley',
      handle: 'gardenGnostic',
      initials: 'GG',
      color: '#4ac925',
      aspect: 'Space',
      playerClass: 'Witch',
      title: 'Witch of Space',
      planet: 'LOFAF',
      planetFull: 'Land of Frost and Frogs',
      dreamMoon: 'Prospit',
      strife: 'Riflekind',
      startWeapon: { id: 'grandpas_rifle', name: "Grandpa's Rifle", atk: 8, icon: '🔫' },
      sylladexModus: 'Bag',
      consorts: 'Turtles',
      consortIcon: '🐢',
      server: 'becquerel',
      client: 'dave',
      denizen: 'Echidna',
      sprite: {
        name: 'Becsprite',
        protoObject: 'Becquerel',
        icon: '🐕',
        power: 'First Guardian power. Teleports projectiles. HP +25.',
        hpBonus: 25, atkBonus: 0,
      },
      questSummary: "Breed the Genesis Frog. As Witch of Space, only you can incubate the universe-embryo. The turtles need your help warming LOFAF's frozen oceans so all frog species can proliferate. Collect DNA samples and breed the perfect specimen — a new universe inside a frog.",
      introMessages: [
        { handle: 'GG', text: "oh my goodness!!" },
        { handle: 'GG', text: "i just got the sburb beta!! did you get it too??" },
        { handle: 'GG', text: "i live on an island in the middle of the ocean so i barely get any mail but today there was a package :)" },
        { handle: 'GG', text: "i already installed the server disc hehehe" },
        { handle: 'GG', text: "bec is looking over my shoulder and he seems interested :o he's such a good dog~~~" },
      ],
      roomDesc: "Your name is JADE HARLEY. You live alone with your dog BEC on a remote island. The house is a FIVE-STORY PAGODA filled with BIZARRE TAXIDERMY courtesy of your late GRANDFATHER, EXOTIC PLANTS you cultivate in the garden, SCIENTIFIC INSTRUMENTS, and a TELESCOPE. You have PROPHETIC DREAMS.",
      icon: '🌸',
      baseHp: 110, baseAtk: 6,
    },
  ],

  // ─── CLASSES ───────────────────────────────────────────────────────────────
  CLASSES: [
    { name: 'Heir',   active: false, desc: 'Inherits and embodies their Aspect. Protected by it.' },
    { name: 'Seer',   active: false, desc: 'Perceives and understands their Aspect. An advisor and strategist.' },
    { name: 'Page',   active: false, desc: 'Provides their Aspect to others. Starts weak, ends powerful.' },
    { name: 'Maid',   active: false, desc: 'Creates or becomes their Aspect.' },
    { name: 'Sylph',  active: false, desc: 'Heals with or through their Aspect.' },
    { name: 'Rogue',  active: false, desc: 'Redistributes their Aspect from enemies to allies.' },
    { name: 'Knight', active: true,  desc: 'Exploits their Aspect as a weapon or tool in combat.' },
    { name: 'Witch',  active: true,  desc: 'Manipulates their Aspect directly and willfully.' },
    { name: 'Mage',   active: true,  desc: 'Knows their Aspect through suffering and personal experience.' },
    { name: 'Bard',   active: true,  desc: 'Passively invites destruction through their Aspect.' },
    { name: 'Prince', active: true,  desc: 'Destroys their Aspect or destroys with their Aspect.' },
    { name: 'Thief',  active: true,  desc: 'Steals their Aspect for themselves.' },
  ],

  // ─── ASPECTS ───────────────────────────────────────────────────────────────
  ASPECTS: [
    { name: 'Breath', icon: '💨', color: '#66ccff', desc: 'Freedom, direction, movement, leadership, wind.' },
    { name: 'Life',   icon: '🌿', color: '#66ff66', desc: 'Vitality, growth, optimism, nature, healing.' },
    { name: 'Light',  icon: '✨', color: '#ffff66', desc: 'Luck, knowledge, information, relevance.' },
    { name: 'Time',   icon: '⏳', color: '#ff8833', desc: 'Time, responsibility, music, doom, repetition.' },
    { name: 'Space',  icon: '🌌', color: '#9966ff', desc: 'Space, creation, the void, the genesis frog.' },
    { name: 'Mind',   icon: '🧠', color: '#66ffee', desc: 'Thought, decisions, justice, consequence.' },
    { name: 'Heart',  icon: '♥',  color: '#ff4488', desc: 'Soul, identity, emotion, the self.' },
    { name: 'Blood',  icon: '🩸', color: '#cc3333', desc: 'Unity, bonds, obligation, belonging.' },
    { name: 'Hope',   icon: '⭐', color: '#ffffcc', desc: 'Belief, potential, positivity, angels.' },
    { name: 'Rage',   icon: '⚡', color: '#aa44ff', desc: 'Limits, fury, negation, nihilism.' },
    { name: 'Doom',   icon: '💀', color: '#447744', desc: 'Death, fate, sacrifice, natural law.' },
    { name: 'Void',   icon: '🌑', color: '#334466', desc: 'Nothingness, secrets, the unknown, erasure.' },
  ],

  // ─── STRIFE SPECIBI ────────────────────────────────────────────────────────
  STRIFE_SPECIBI: [
    { name: 'Hammerkind', icon: '🔨', startWeaponId: 'crappy_sledgehammer', special: 'DOUBLE HAMMER',    specialDesc: 'Smash the enemy twice in rapid succession.' },
    { name: 'Bladekind',  icon: '⚔️',  startWeaponId: 'broken_sword',        special: 'CALEDFWLCH',       specialDesc: 'A legendary sword slash — high critical chance.' },
    { name: 'Needlekind', icon: '🪡', startWeaponId: 'knitting_needles',     special: 'FRAYMOTIF: RAIN',  specialDesc: 'A storm of needles strikes all enemies.' },
    { name: 'Riflekind',  icon: '🔫', startWeaponId: 'grandpas_rifle',       special: 'AIMED SHOT',       specialDesc: 'A precision long-range strike. High damage.' },
    { name: '2x4kind',    icon: '🪵', startWeaponId: 'plank',                special: 'SPLINTER WAVE',    specialDesc: 'A wide-arc sweep hits multiple targets.' },
    { name: 'Wandkind',   icon: '🪄', startWeaponId: 'magic_cue_ball',       special: 'ZILLYHOO',         specialDesc: 'Unpredictable chaos blast.' },
    { name: 'Bowkind',    icon: '🏹', startWeaponId: 'homemade_bow',         special: 'ARROW RAIN',       specialDesc: 'Fires a volley of arrows at all enemies.' },
    { name: 'Clubkind',   icon: '🏏', startWeaponId: 'cricket_bat',          special: 'BATTER UP',        specialDesc: 'Knocks the enemy skyward for bonus damage.' },
  ],

  // ─── SYLLADEX FETCH MODI ───────────────────────────────────────────────────
  SYLLADEX_MODI: [
    { name: 'Stack',    capacity: 10, desc: 'LIFO. Only the top card is accessible. Pick up an item, everything else gets pushed down.' },
    { name: 'Queue',    capacity: 10, desc: 'FIFO. Items form a line. The oldest item comes out first. Bad for grabbing what you need quickly.' },
    { name: 'Array',    capacity: 12, desc: 'Items stored by index. Specify the wrong index and every card ABOVE that slot gets ejected — destructively.' },
    { name: 'Hash Map', capacity: 10, desc: 'Items stored by keyword. Fast lookup if you remember the key. Hash collisions cause random ejections.' },
    { name: 'Tree',     capacity: 15, desc: 'Binary tree. Leaf nodes are accessible. Must remove leaves before inner nodes. High capacity.' },
    { name: 'Bag',      capacity: 20, desc: 'Totally random retrieval. Reach in and grab whatever. Chaotic — but anything could come out at any time.' },
  ],

  // ─── GRIST TYPES ───────────────────────────────────────────────────────────
  GRIST_TYPES: [
    { id: 'build',    name: 'Build Grist', color: '#aaaaaa', icon: '⬜', desc: 'Universal construction grist. All underlings drop it.' },
    { id: 'shale',    name: 'Shale',       color: '#6666aa', icon: '🪨', desc: 'From low-tier imps.' },
    { id: 'marble',   name: 'Marble',      color: '#ddddee', icon: '⚪', desc: 'From ogres.' },
    { id: 'obsidian', name: 'Obsidian',    color: '#8833cc', icon: '🟣', desc: 'From basilisks.' },
    { id: 'tar',      name: 'Tar',         color: '#886600', icon: '🟫', desc: 'Mid-tier enemies.' },
    { id: 'ruby',     name: 'Ruby',        color: '#ff0044', icon: '🔴', desc: 'From liches and rare enemies.' },
    { id: 'amber',    name: 'Amber',       color: '#ffaa00', icon: '🟡', desc: "Denizens' minions." },
    { id: 'cobalt',   name: 'Cobalt',      color: '#0055ff', icon: '🔵', desc: 'High-tier constructs.' },
    { id: 'iodine',   name: 'Iodine',      color: '#660088', icon: '🟪', desc: 'Near denizen lairs.' },
    { id: 'quartz',   name: 'Quartz',      color: '#eeeeff', icon: '💠', desc: 'Near consort villages.' },
  ],

  // ─── PHERNALIA ─────────────────────────────────────────────────────────────
  PHERNALIA: [
    {
      id: 'cruxtruder',
      name: 'Cruxtruder',
      icon: '🔩',
      step: 1,
      desc: 'A large cylindrical machine. The server player REMOVES THE LID. A Cruxite Dowel is extruded, the Kernelsprite emerges, and a METEOR COUNTDOWN begins.',
      requires: null,
    },
    {
      id: 'totem_lathe',
      name: 'Totem Lathe',
      icon: '🗜️',
      step: 2,
      desc: 'Insert a Cruxite Dowel and a Punched Card. The lathe carves the dowel into a Cruxite Totem matching the card\'s hole pattern.',
      requires: 'cruxtruder',
    },
    {
      id: 'punch_designix',
      name: 'Punch Designix',
      icon: '🖨️',
      step: 3,
      desc: 'Insert a Captchalogue Card and an item to scan. The Designix punches the item\'s captcha code into the card. Combine codes with && (double-punch) or || (ghost-punch) to alchemize hybrid items.',
      requires: null,
    },
    {
      id: 'alchemiter',
      name: 'Alchemiter',
      icon: '⚗️',
      step: 4,
      desc: 'Place a Cruxite Totem on the platform. The Alchemiter manifests the item encoded in the totem. Your Entry Item is created here. Smash it to enter the Medium.',
      requires: 'totem_lathe',
    },
  ],

  // ─── ALCHEMY ITEMS ─────────────────────────────────────────────────────────
  ALCHEMY_ITEMS: [
    // Base items
    { id: 'crappy_sledgehammer',  name: 'Crappy Sledgehammer',           icon: '🔨', type: 'weapon', specibus: 'Hammerkind', atk: 4,  def: 0,  captchaCode: '01XWY00Q', desc: 'A beat-up hammer. Gets the job done.' },
    { id: 'broken_sword',         name: 'Broken Sword of the 21st Cen.', icon: '⚔️',  type: 'weapon', specibus: 'Bladekind',  atk: 3,  def: 0,  captchaCode: '0000G7V6', desc: 'A sword. Broken. Ironic.' },
    { id: 'knitting_needles',     name: 'Knitting Needles',               icon: '🪡', type: 'weapon', specibus: 'Needlekind', atk: 5,  def: 0,  captchaCode: '00002B!S', desc: 'Sharp. Surprisingly effective.' },
    { id: 'grandpas_rifle',       name: "Grandpa's Rifle",                icon: '🔫', type: 'weapon', specibus: 'Riflekind',  atk: 8,  def: 0,  captchaCode: 'G00RF1LE', desc: 'An heirloom rifle. Still fires.' },
    { id: 'wrench',               name: 'Wrench',                         icon: '🔧', type: 'weapon', specibus: 'Hammerkind', atk: 5,  def: 0,  captchaCode: '01WRENCH', desc: 'A trusty wrench.' },
    { id: 'colonel_sassacre',     name: "Colonel Sassacre's Compendium",  icon: '📖', type: 'junk',   specibus: null,          atk: 0,  def: 0,  captchaCode: 'CSSACRES', desc: 'A daunting tome. Heavy.' },
    { id: 'lil_cal',              name: 'Lil Cal',                        icon: '🤡', type: 'junk',   specibus: null,          atk: 0,  def: 0,  captchaCode: 'L1LCA10O', desc: "Bro's puppet. Don't look at its eyes." },
    { id: 'plank',                name: 'Plank of Wood',                  icon: '🪵', type: 'weapon', specibus: '2x4kind',     atk: 5,  def: 0,  captchaCode: 'PL4NK00W', desc: 'A 2x4. Simple but effective.' },
    { id: 'magic_cue_ball',       name: 'Magic Cue Ball',                 icon: '🎱', type: 'weapon', specibus: 'Wandkind',    atk: 6,  def: 0,  captchaCode: 'M4GCUBAL', desc: 'A magic 8-ball repurposed as a weapon.' },
    { id: 'homemade_bow',         name: 'Homemade Bow',                   icon: '🏹', type: 'weapon', specibus: 'Bowkind',     atk: 7,  def: 0,  captchaCode: 'H0MBOW00', desc: 'Crafted from a tree branch and string.' },
    { id: 'cricket_bat',          name: 'Cricket Bat',                    icon: '🏏', type: 'weapon', specibus: 'Clubkind',    atk: 6,  def: 0,  captchaCode: 'CR1CKET0', desc: 'For cricket. Or combat.' },
    // Alchemized weapons
    { id: 'wrinklefucker',        name: 'Wrinklefucker',                  icon: '🔨', type: 'weapon', specibus: 'Hammerkind', atk: 12, def: 0,  captchaCode: 'WRINKLFK', recipe: { a: '01WRENCH', b: '01WRENCH', op: '&&' }, grist: { build: 30, shale: 10 },         desc: 'Hammer && Wrench. Double-headed. Very painful.' },
    { id: 'fear_no_anvil',        name: 'Fear No Anvil',                  icon: '⚒️',  type: 'weapon', specibus: 'Hammerkind', atk: 24, def: 0,  captchaCode: 'FEARNVL0', recipe: { a: 'WRINKLFK', b: '01XWY00Q', op: '&&' }, grist: { build: 80, marble: 20, tar: 10 }, desc: 'The legendary Fear No Anvil. Forged from nothing but raw determination.' },
    { id: 'caledfwlch',           name: 'Caledfwlch',                     icon: '🗡️',  type: 'weapon', specibus: 'Bladekind',  atk: 18, def: 0,  captchaCode: 'CALEDFWL', recipe: { a: '0000G7V6', b: 'CSSACRES', op: '&&' }, grist: { build: 60, shale: 15 },          desc: 'The broken sword and the legendary tome, combined. Slightly less broken.' },
    { id: 'warhammer_of_zillyhoo',name: 'Warhammer of Zillyhoo',          icon: '🔨', type: 'weapon', specibus: 'Hammerkind', atk: 20, def: 0,  captchaCode: 'Z1LLYHOO', recipe: { a: 'HARLQNDL', b: 'M4GCUBAL', op: '||' }, grist: { build: 100, amber: 25 },          desc: 'A magnificent rainbow hammer. It honks when it lands a hit.' },
    { id: 'cosbytop',             name: 'Cosbytop',                       icon: '🧥', type: 'armor',  specibus: null,          atk: 0,  def: 15, captchaCode: 'C0SBYT0P', recipe: { a: '00002B!S', b: 'YARNYARN', op: '&&' }, grist: { build: 40, marble: 10 },          desc: 'A knit sweater that somehow functions as armor.' },
    { id: 'god_tier_cape',        name: 'God Tier Cape',                  icon: '✨', type: 'armor',  specibus: null,          atk: 0,  def: 30, captchaCode: 'G0DT1ER0', recipe: { a: 'ASPECTXX', b: 'SKAIADNX', op: '&&' }, grist: { build: 200, ruby: 50, cobalt: 30, iodine: 20 }, desc: 'Imbued with your Aspect. Grants immortality... unless your death is Heroic or Just.' },
    // Entry items
    { id: 'cruxite_apple',        name: 'Cruxite Apple',                  icon: '🍎', type: 'entry',  specibus: null,          atk: 0,  def: 0,  captchaCode: 'APPLECRX', forKid: 'john', grist: { build: 50 }, desc: "John's entry item. Smash it to enter the Medium." },
    { id: 'cruxite_bottle',       name: 'Cruxite Bottle',                 icon: '🍶', type: 'entry',  specibus: null,          atk: 0,  def: 0,  captchaCode: 'BOTTLCRX', forKid: 'rose', grist: { build: 50 }, desc: "Rose's entry item. Drink it to enter the Medium." },
    { id: 'cruxite_record',       name: 'Cruxite Record',                 icon: '📀', type: 'entry',  specibus: null,          atk: 0,  def: 0,  captchaCode: 'RCRDCRX0', forKid: 'dave', grist: { build: 50 }, desc: "Dave's entry item. Drop it to enter the Medium." },
    { id: 'cruxite_sphere',       name: 'Cruxite Sphere',                 icon: '🔮', type: 'entry',  specibus: null,          atk: 0,  def: 0,  captchaCode: 'SPHERCRX', forKid: 'jade', grist: { build: 50 }, desc: "Jade's entry item. It hums faintly." },
  ],

  // ─── ENEMIES (Underlings) ──────────────────────────────────────────────────
  ENEMIES: [
    {
      id: 'imp', name: 'Shale Imp', tier: 1, icon: '👹',
      art: ['  /\\__/\\  ', ' ( >.< ) ', '  > ^ <  ', ' /|   |\\ '],
      hp: 25, maxHp: 25, atk: 5, def: 1,
      grist: { build: 8, shale: 2 }, xp: 12,
      desc: 'Small, nimble imps. The weakest underlings.',
    },
    {
      id: 'ogre', name: 'Underling Ogre', tier: 2, icon: '👾',
      art: ['  /O  O\\ ', ' |  ___  |', '  \\___/ ', ' /|   |\\ '],
      hp: 80, maxHp: 80, atk: 14, def: 5,
      grist: { build: 30, marble: 8, shale: 4 }, xp: 50,
      desc: 'Large brutes. Slow but hits hard.',
    },
    {
      id: 'basilisk', name: 'Basilisk', tier: 2, icon: '🐍',
      art: [' __===__ ', '(  o  o )', ' \\~~~~~/ ', '  ||||| '],
      hp: 55, maxHp: 55, atk: 10, def: 3,
      grist: { build: 20, obsidian: 6, shale: 3 }, xp: 35,
      desc: 'Serpentine underlings. Their gaze can paralyze.',
    },
    {
      id: 'lich', name: 'Lich', tier: 3, icon: '💀',
      art: ['   ___ ', '  /x x\\ ', ' | ___ | ', '  \\___/ ', '  |___| '],
      hp: 130, maxHp: 130, atk: 20, def: 8,
      grist: { build: 60, ruby: 12, tar: 10 }, xp: 110,
      desc: 'Undead sorcerers. Powerful spellcasters.',
    },
    {
      id: 'giclops', name: 'Giclops', tier: 3, icon: '🧿',
      art: ['  (O__) ', '  |___| ', ' /|   |\\ '],
      hp: 200, maxHp: 200, atk: 25, def: 12,
      grist: { build: 100, amber: 20, cobalt: 10 }, xp: 200,
      desc: 'A massive one-eyed monstrosity.',
    },
    {
      id: 'denizen', name: 'The Denizen', tier: 4, icon: '🐉',
      art: [' ~~~===~~~ ', '( 0  . . 0 )', ' \\  ___  / ', '  |     |  ', '  |_____|  '],
      hp: 9999, maxHp: 9999, atk: 50, def: 20,
      grist: { build: 500, iodine: 100, ruby: 50, cobalt: 50 }, xp: 5000,
      desc: 'The Denizen at the core of your planet. Face it.',
    },
  ],

  // ─── ECHELADDER ────────────────────────────────────────────────────────────
  ECHELADDER: [
    { rung:  1, name: 'Pupa Pan',              xp: 0,    hpBonus: 0,  atkBonus: 0  },
    { rung:  2, name: 'Pony Rider',            xp: 30,   hpBonus: 5,  atkBonus: 1  },
    { rung:  3, name: 'Squabbling Squire',      xp: 80,   hpBonus: 5,  atkBonus: 1  },
    { rung:  4, name: 'Daring Dastard',         xp: 160,  hpBonus: 10, atkBonus: 2  },
    { rung:  5, name: 'Gallant Galloot',        xp: 280,  hpBonus: 10, atkBonus: 2  },
    { rung:  6, name: 'Formidable Fighter',     xp: 450,  hpBonus: 15, atkBonus: 3  },
    { rung:  7, name: 'Paragon Pirate',         xp: 680,  hpBonus: 15, atkBonus: 3  },
    { rung:  8, name: 'Heroic Hoodlum',         xp: 980,  hpBonus: 20, atkBonus: 4  },
    { rung:  9, name: 'Legendary Loser',        xp: 1350, hpBonus: 20, atkBonus: 4  },
    { rung: 10, name: 'Wicked Windbag',         xp: 1800, hpBonus: 25, atkBonus: 5  },
    { rung: 11, name: 'Awkward Ambler',         xp: 2350, hpBonus: 25, atkBonus: 5  },
    { rung: 12, name: 'Bane of the Hemospectrum', xp: 3000, hpBonus: 30, atkBonus: 6 },
    { rung: 13, name: 'Heir Transparent',       xp: 3750, hpBonus: 35, atkBonus: 7  },
    { rung: 14, name: 'Seer of Visions',        xp: 4600, hpBonus: 40, atkBonus: 8  },
    { rung: 15, name: 'God Tier Candidate',     xp: 5500, hpBonus: 50, atkBonus: 10 },
  ],

  // ─── KERNELSPRITE PROTOTYPING OPTIONS ─────────────────────────────────────
  SPRITE_OBJECTS: [
    { id: 'nanna_ashes', name: "Nanna's Ashes",          icon: '⚱️', power: 'Nannasprite. Gives advice and cooking tips. HP +15.',          hpBonus: 15, atkBonus: 0  },
    { id: 'jaspers',     name: 'Jaspers the Cat',         icon: '🐈', power: 'Jaspersprite. Cryptic guidance. ATK +10.',                     hpBonus: 0,  atkBonus: 10 },
    { id: 'lil_cal_s',   name: 'Lil Cal Puppet',          icon: '🤡', power: 'Calsprite. Enemies sometimes flee in terror. ATK +5. HP +5.', hpBonus: 5,  atkBonus: 5  },
    { id: 'bec_s',       name: 'Becquerel',               icon: '🐕', power: 'Becsprite. First Guardian power. Teleports attacks. HP +25.',  hpBonus: 25, atkBonus: 0  },
    { id: 'wizard',      name: 'Wizard Statue',           icon: '🧙', power: 'Wizardsprite. Magic bonus. ATK +8. HP +5.',                    hpBonus: 5,  atkBonus: 8  },
    { id: 'crow',        name: 'Crow',                    icon: '🐦', power: 'Crowsprite. Scouting — reveals enemy stats before battle.',   hpBonus: 5,  atkBonus: 3  },
    { id: 'frog_s',      name: 'Frog',                    icon: '🐸', power: 'Frogsprite. Prophetic. Unlocks Space powers early.',           hpBonus: 0,  atkBonus: 0  },
    { id: 'sword_s',     name: 'Sword',                   icon: '🗡️',  power: 'Swordsprite. Combat aura. ATK +12.',                          hpBonus: 0,  atkBonus: 12 },
    { id: 'tome',        name: 'Tome of Eldritch Lore',   icon: '📕', power: 'Grimsprite. Channels Outer Gods. ATK +20. HP -10. Risky.',    hpBonus: -10, atkBonus: 20 },
    { id: 'harlequin',   name: 'Harlequin Doll',          icon: '🎭', power: 'Clownsprite. Honk blast AoE. Confuses enemies.',              hpBonus: 10, atkBonus: 5  },
  ],

  // ─── PLANETS ───────────────────────────────────────────────────────────────
  PLANETS: [
    {
      aspect: 'Breath',     id: 'lowas', abbrev: 'LOWAS', name: 'Land of Wind and Shade',
      color: '#3355aa', skyColor: '#050520', consort: 'Salamanders', consortIcon: '🦎',
      denizen: 'Typheus',
      desc: 'A perpetually dark world of howling wind and billowing smoke. Countless oil pipelines snake the surface, connecting to smokestacks that blacken the sky. The Salamanders wait for the Heir of Breath.',
      quest: 'Free the wind from the underground pipelines. Clear the smoke. Let the light of Skaia reach the surface again.',
    },
    {
      aspect: 'Light',      id: 'lolar', abbrev: 'LOLAR', name: 'Land of Light and Rain',
      color: '#aaaa22', skyColor: '#1a1a00', consort: 'Iguanas', consortIcon: '🦎',
      denizen: 'Nix',
      desc: "A world of blinding light and perpetual rainfall. The iguanas have built canal systems to manage the floods. The rain comes from Skaia's light refracting through smoke clouds.",
      quest: "Clear the smoke obscuring Skaia's light. Defeat the Rainbow Drinker cult siphoning the light.",
    },
    {
      aspect: 'Time',       id: 'lohac', abbrev: 'LOHAC', name: 'Land of Heat and Clockwork',
      color: '#cc4400', skyColor: '#1a0500', consort: 'Crocodiles', consortIcon: '🐊',
      denizen: 'Hephaestus',
      desc: 'A world of volcanic heat and massive interlocking clockwork gears. The planet itself is a clock mechanism that has ground to a halt. The Crocodiles have lost their sense of time.',
      quest: 'Repair the broken clockwork. Oil the gears. Restore the flow of time to LOHAC.',
    },
    {
      aspect: 'Space',      id: 'lofaf', abbrev: 'LOFAF', name: 'Land of Frost and Frogs',
      color: '#4499aa', skyColor: '#000a10', consort: 'Turtles', consortIcon: '🐢',
      denizen: 'Echidna',
      desc: 'A frozen world of tundra and glaciers. Countless frog species live in the icy ponds. The Turtles revere the frogs. Only the Witch of Space can breed the Genesis Frog here.',
      quest: 'Breed the Genesis Frog by collecting DNA from all frog species across LOFAF. The universe depends on it.',
    },
    {
      aspect: 'Mind',       id: 'lomat', abbrev: 'LOMAT', name: 'Land of Maps and Treasure',
      color: '#33aa88', skyColor: '#001510', consort: 'Turtles', consortIcon: '🐢',
      denizen: 'Hemera',
      desc: 'A world of endless contradictory maps and hidden treasures.',
      quest: 'Chart the unmappable labyrinth and recover the Treasure of Skaia.',
    },
    {
      aspect: 'Heart',      id: 'loraf', abbrev: 'LORAF', name: 'Land of Rays and Frogs',
      color: '#cc2255', skyColor: '#15000a', consort: 'Turtles', consortIcon: '🐢',
      denizen: 'Nix',
      desc: 'A world of warm sunlight and leaping frogs. The soul resonates with the Heart aspect.',
      quest: 'Restore the identity of the lost souls wandering LORAF.',
    },
    {
      aspect: 'Blood',      id: 'lopah', abbrev: 'LOPAH', name: 'Land of Pulse and Haze',
      color: '#992222', skyColor: '#100005', consort: 'Crocodiles', consortIcon: '🐊',
      denizen: 'Typheus',
      desc: 'A misty world of rhythmic pulsing. Bonds here are everything.',
      quest: 'Unite the divided crocodile tribes of LOPAH.',
    },
    {
      aspect: 'Hope',       id: 'lowaa', abbrev: 'LOWAA', name: 'Land of Wrath and Angels',
      color: '#ccccaa', skyColor: '#101010', consort: 'Turtles', consortIcon: '🐢',
      denizen: 'Hemera',
      desc: 'A world of angelic architecture and simmering divine fury. Angels wage endless war here.',
      quest: 'Pacify the Angels of LOWAA. Channel hope, not wrath.',
    },
    {
      aspect: 'Rage',       id: 'lotam', abbrev: 'LOTAM', name: 'Land of Tents and Mirth',
      color: '#7744cc', skyColor: '#080010', consort: 'Iguanas', consortIcon: '🦎',
      denizen: 'Nix',
      desc: 'A world of colorful tents and inexplicable humor. Nothing makes sense here.',
      quest: 'Find the source of the inexplicable mirth and extinguish it.',
    },
    {
      aspect: 'Doom',       id: 'lotak', abbrev: 'LOTAK', name: 'Land of Tombs and Krypton',
      color: '#336644', skyColor: '#000a00', consort: 'Salamanders', consortIcon: '🦎',
      denizen: 'Typheus',
      desc: 'A world of ancient tombs and strange radioactive minerals. Death is omnipresent here.',
      quest: 'Fulfill the doom written in the ancient tombs. Accept fate.',
    },
    {
      aspect: 'Void',       id: 'locah', abbrev: 'LOCAH', name: 'Land of Crypts and Helium',
      color: '#223355', skyColor: '#010108', consort: 'Turtles', consortIcon: '🐢',
      denizen: 'Nix',
      desc: 'A dark world of whispering crypts and strange floating gas. The void speaks here.',
      quest: 'Unseal the Crypts of Nothing. Confront the emptiness.',
    },
    {
      aspect: 'Life',       id: 'lolar2', abbrev: 'LOLAR', name: 'Land of Little Cubes and Tea',
      color: '#66cc66', skyColor: '#0a100a', consort: 'Turtles', consortIcon: '🐢',
      denizen: 'Hemera',
      desc: 'A world of tiny cubes and an inexplicable amount of tea.',
      quest: 'Bring warmth to the frozen tea. Nurture life.',
    },
  ],

  // ─── INCIPISPHERE ──────────────────────────────────────────────────────────
  MEDIUM: {
    skaia:        { name: 'Skaia',          icon: '🔵', color: '#3366ff', desc: "The Battlefield. A giant blue orb at the heart of the Incipisphere. Shows visions of past and future. The White armies of Prospit defend it from the Black armies of Derse. This is where the final battle will be fought." },
    prospit:      { name: 'Prospit',        icon: '🌕', color: '#ffdd00', desc: "The golden moon. City of gold where the White King and White Queen reign. Dreamers of Prospit — John and Jade — have golden Dream Selves who wander the towers and gaze at Skaia's visions." },
    derse:        { name: 'Derse',          icon: '🌑', color: '#9933cc', desc: "The purple moon. The Black King and Black Queen command the dark armies from here. Dreamers of Derse — Rose and Dave — have purple Dream Selves scheming in its towers." },
    furthestRing: { name: 'The Furthest Ring', icon: '🌌', color: '#001133', desc: "Beyond the Veil — where the Horrorterrors dwell. Vast, incomprehensible Outer Gods. Rose can hear them. They say the game cannot be won by conventional means." },
    veil:         { name: 'The Veil',       icon: '🌫️', color: '#224455', desc: "The asteroid field between the Medium and the Furthest Ring. Various asteroids contain laboratories and important artifacts." },
  },

  // ─── CONSORT DIALOGUE ──────────────────────────────────────────────────────
  CONSORT_DIALOGUE: {
    salamanders: [
      "The wind! We have been waiting so long for the wind to return.",
      "The pipes run deep, young heir. The smoke chokes everything. Please free us.",
      "Long ago, before the age of pipes, we could breathe freely. The sky was clear.",
      "The underground passages hold the key to freeing the wind currents.",
      "We believe in you, Heir of Breath. The wind whispers your name.",
    ],
    iguanas: [
      "The light is both too much and not enough. This is a paradox only a Seer can resolve.",
      "The rain comes from Skaia above, but something in the clouds corrupts it.",
      "The Rainbow Drinkers grow stronger. They siphon the light for themselves, leaving us in darkness.",
      "We have heard of the Seer — one who perceives truth within light's chaos.",
      "Perhaps you can see what we cannot, Seer of Light.",
    ],
    crocodiles: [
      "THE GEARS HAVE STOPPED. Time on this world has HALTED. Do you understand how UNCOOL that is?",
      "The clockwork runs EVERYWHERE. It IS our world. Without it, everything is FROZEN.",
      "We crocodiles have always RESPECTED time. Now time doesn't respect us back.",
      "The gears need oil. We have oil — but something keeps clogging the WORKS.",
      "Get those gears turning, Knight. It's literally what you were born to do.",
    ],
    turtles: [
      "The frogs sing of creation. Can you hear them singing?",
      "The Genesis Frog must be bred from all frog species. A cosmic responsibility.",
      "We have been tending these frozen ponds for a very long time.",
      "The ice must melt — but only just enough. The Witch of Space can control the balance.",
      "The universe depends on the frog. It always has, and it always will.",
    ],
  },

  // ─── SKAIA VISIONS ─────────────────────────────────────────────────────────
  SKAIA_VISIONS: [
    "You see a vision of your friends, laughing together on a new world under twin suns.",
    "You see yourself, older and wiser, standing at the edge of a newly created universe.",
    "You see the Black King on the Battlefield, growing taller with every prototyping your session completes.",
    "You see a hundred branching timelines — most collapsing, a few surviving.",
    "You see a frog. Just a frog. Sitting in a pond. Somehow this is the most important image you have ever witnessed.",
    "You see your Dream Self gazing back at Skaia from below, seeing the same vision in reverse.",
    "You see the Scratch — a reset — and new versions of you being born into a changed world.",
    "You see the Genesis Frog, fully formed, containing entire galaxies within its ancient eyes.",
    "You see the Horrorterrors writhing at the edges of everything, whispering that this session cannot be won.",
    "You see a green sun — immense and terrible — and feel that it is somehow important to your survival.",
  ],

  // ─── BLACK KING ────────────────────────────────────────────────────────────
  BLACK_KING: {
    name: 'The Black King',
    icon: '♛',
    hp: 5000, maxHp: 5000, atk: 80, def: 25,
    desc: "The final boss of the SBURB session. His power scales with every prototyping — he gains the features of every prototype in the session. The more you prototype, the stronger he becomes. Defeat him to claim the Ultimate Reward.",
    grist: { build: 1000, ruby: 200, iodine: 100, cobalt: 100 },
    xp: 9999,
  },

  // ─── ULTIMATE REWARD ───────────────────────────────────────────────────────
  ULTIMATE_REWARD: {
    name: 'The Ultimate Reward',
    icon: '🌟',
    desc: "A new universe is created. The winning players become its gods. This new universe is not the world they came from — it is a fresh creation teeming with life. This is the true purpose of SBURB: not to save the players' world, but to bring a new one into being.",
  },

  // ─── GOD TIER ──────────────────────────────────────────────────────────────
  GOD_TIER: {
    desc: "When a player dies on their Quest Bed on their land, they ascend to God Tier. Their injuries heal. They are reborn in a costume representing their Class and Aspect, and granted immortality — unless their death is deemed Just or Heroic by the forces of paradox space.",
    outfits: {
      john: { name: 'Heir of Breath',  icon: '💨', color: '#3388ff', desc: 'Blue bodysuit with flowing wings. The wind itself obeys you.' },
      rose: { name: 'Seer of Light',   icon: '✨', color: '#b536da', desc: 'Purple robe with golden trim. You perceive all relevant information.' },
      dave: { name: 'Knight of Time',  icon: '⏳', color: '#cc4400', desc: 'Red knight armor. You wield time itself as a weapon.' },
      jade: { name: 'Witch of Space',  icon: '🌌', color: '#4ac925', desc: 'Green dress with a planet in its folds. You control space and scale itself.' },
    },
  },

  // ─── ROOM OBJECTS ──────────────────────────────────────────────────────────
  ROOM_OBJECTS: {
    john: [
      { id: 'hammer',       name: 'Crappy Sledgehammer', icon: '🔨', captchaCode: '01XWY00Q', desc: 'A hammer. Perfect for hammerkind.',         canCaptchalogue: true,  itemId: 'crappy_sledgehammer', action: null },
      { id: 'colonel_book', name: "Colonel Sassacre's",  icon: '📖', captchaCode: 'CSSACRES', desc: 'Very large, very heavy book of magic jokes.', canCaptchalogue: true,  itemId: 'colonel_sassacre',    action: null },
      { id: 'nanna_ashes',  name: "Nanna's Ashes",       icon: '⚱️', captchaCode: 'NANNAASH', desc: 'An urn of your late grandmother\'s ashes.',  canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'harlequin',    name: 'Harlequin Doll',      icon: '🎭', captchaCode: 'HARLQNDL', desc: 'A creepy harlequin doll. Dad loves these.',  canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'ghostbusters', name: 'Ghostbusters Poster', icon: '🎬', captchaCode: null,        desc: "You love Ghostbusters. It never gets old.",  canCaptchalogue: false, itemId: null,                  action: null },
      { id: 'cake',         name: "Dad's Birthday Cake", icon: '🎂', captchaCode: null,        desc: 'Dad made you a cake. It has a harlequin on it.', canCaptchalogue: false, itemId: null,              action: null },
      { id: 'computer',     name: 'Computer',            icon: '💻', captchaCode: null,        desc: 'Your computer. Pesterchum is open.',        canCaptchalogue: false, itemId: null,                  action: 'pesterchum' },
      { id: 'sburb_disc',   name: 'SBURB Client Disc',   icon: '💿', captchaCode: null,        desc: 'The SBURB beta. Time to install.',           canCaptchalogue: false, itemId: null,                  action: 'install' },
    ],
    rose: [
      { id: 'needles',      name: 'Knitting Needles',     icon: '🪡', captchaCode: '00002B!S', desc: 'Needlekind strife weapon.',                  canCaptchalogue: true,  itemId: 'knitting_needles',    action: null },
      { id: 'jaspers',      name: 'Jaspers (stuffed)',    icon: '🐈', captchaCode: 'JASPRSCT', desc: 'Your late cat, taxidermied by Mom.',         canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'wizard',       name: 'Wizard Figurine',      icon: '🧙', captchaCode: 'WZRDSTAT', desc: 'One of many wizards Mom left around.',       canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'tome',         name: 'Tome of Eldritch Lore',icon: '📕', captchaCode: 'ELDRTOME', desc: "A book you probably shouldn't read.",        canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'yarn',         name: 'Yarn',                 icon: '🧶', captchaCode: 'YARNYARN', desc: 'Yarn for knitting. There is a lot of it.',  canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'computer',     name: 'Computer',             icon: '💻', captchaCode: null,        desc: 'Your computer.',                            canCaptchalogue: false, itemId: null,                  action: 'pesterchum' },
      { id: 'sburb_disc',   name: 'SBURB Client Disc',    icon: '💿', captchaCode: null,        desc: 'The SBURB beta.',                           canCaptchalogue: false, itemId: null,                  action: 'install' },
    ],
    dave: [
      { id: 'sword',        name: 'Broken Sword',         icon: '⚔️',  captchaCode: '0000G7V6', desc: 'A sword. Broken. Ironic.',                  canCaptchalogue: true,  itemId: 'broken_sword',        action: null },
      { id: 'lil_cal',      name: 'Lil Cal',              icon: '🤡', captchaCode: 'L1LCA10O', desc: "Bro's puppet. Something is wrong with it.", canCaptchalogue: true,  itemId: 'lil_cal',             action: null },
      { id: 'turntables',   name: 'Turntables',           icon: '🎵', captchaCode: null,        desc: 'Your DJ setup. Hella tight.',               canCaptchalogue: false, itemId: null,                  action: null },
      { id: 'camera',       name: 'Sweet Camera',         icon: '📷', captchaCode: 'SWETCAM0', desc: 'For amateur photography.',                  canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'ironic_art',   name: 'Ironic Horseshoe Art', icon: '🖼️',  captchaCode: null,        desc: 'Ironic. Or is it?',                         canCaptchalogue: false, itemId: null,                  action: null },
      { id: 'computer',     name: 'Computer',             icon: '💻', captchaCode: null,        desc: 'Pesterchum open. Several windows.',         canCaptchalogue: false, itemId: null,                  action: 'pesterchum' },
      { id: 'sburb_disc',   name: 'SBURB Client Disc',    icon: '💿', captchaCode: null,        desc: "One of Bro's server discs.",                canCaptchalogue: false, itemId: null,                  action: 'install' },
    ],
    jade: [
      { id: 'rifle',        name: "Grandpa's Rifle",      icon: '🔫', captchaCode: 'G00RF1LE', desc: "Grandpa's rifle. Riflekind.",                canCaptchalogue: true,  itemId: 'grandpas_rifle',      action: null },
      { id: 'telescope',    name: 'Telescope',            icon: '🔭', captchaCode: null,        desc: 'For gazing at Skaia.',                      canCaptchalogue: false, itemId: null,                  action: null },
      { id: 'plant',        name: 'Exotic Plant',         icon: '🌺', captchaCode: 'EXTICPLT', desc: 'One of your garden plants.',                canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'frog',         name: 'Frog',                 icon: '🐸', captchaCode: 'FR0GFROG', desc: 'A frog. It knows something.',               canCaptchalogue: true,  itemId: null,                  action: null },
      { id: 'bec',          name: 'Becquerel',            icon: '🐕', captchaCode: null,        desc: 'Your dog. The First Guardian. Good boy.',   canCaptchalogue: false, itemId: null,                  action: null },
      { id: 'taxidermy',    name: "Grandpa's Taxidermy",  icon: '🦁', captchaCode: null,        desc: "Grandpa's stuffed animals. Lots of them.",  canCaptchalogue: false, itemId: null,                  action: null },
      { id: 'computer',     name: 'Computer',             icon: '💻', captchaCode: null,        desc: 'Pesterchum! You love your friends :)',       canCaptchalogue: false, itemId: null,                  action: 'pesterchum' },
      { id: 'sburb_disc',   name: 'SBURB Beta (Server)',  icon: '💿', captchaCode: null,        desc: 'Already installed the server disc :)',       canCaptchalogue: false, itemId: null,                  action: 'install' },
    ],
  },

  // ─── FRAYMOTIFS ─────────────────────────────────────────────────────────────
  FRAYMOTIFS: [
    { id: 'pop_a_top', name: 'Pop A Top',    cost: 50, users: ['john'], desc: 'Heir of Breath sends a gale-force wind blast.', dmg: 40, target: 'all'    },
    { id: 'rain',      name: 'Rain',         cost: 60, users: ['rose'], desc: 'Seer of Light calls down a storm of needles.',  dmg: 50, target: 'all'    },
    { id: 'turnabout', name: 'Turnabout',    cost: 70, users: ['dave'], desc: 'Knight of Time rewinds 3 seconds of the fight.', dmg: 35, target: 'single' },
    { id: 'green_sun', name: 'Green Sun',    cost: 80, users: ['jade'], desc: 'Witch of Space flings enemies into the Green Sun.', dmg: 60, target: 'all' },
  ],

};

export default CONFIG;
